name: update data

on:
  schedule:
   - cron: "20 14 18 * *"
   
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull latest Docker image and start services
      run: |
        docker compose pull
        docker compose up -d

    - name: wait for Airflow to start
      run: make wait_for_airflow
    
    - name: run DAG
      run: make run_dag_GHActions

    - name: Wait for DAG completion
      run: sleep 120
      
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Ran the DAGs and updated the data"
        push_options: '--force'

